apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sleep", "60"]
      restartPolicy: Never
  backoffLimit: 4
