apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 4
